language: python
python:
#  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - "pip install -e .[test]"
  - "pip install coveralls"
# command to run tests
script: tox
# coverage
after_success:
  - coveralls

  matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35