language: python
python:
  - "3.5"
#  matrix:
#    - TOXENV=py27
#    - TOXENV=py35
# command to install dependencies
install:
  - "pip install -e .[test]"
  - "pip install coveralls"
# command to run tests
script: tox
# coverage
after_success:
  - coveralls
